### ISSUE TITLE
WidgetsBinding.instance.addPostFrameCallback failed

### ISSUE THREAD

**Issue by caiomourasud** [hadukin/custom_sliding_segmented_control#18]
Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'.

**Comment by momo1110111** [comment]
Me too.

**Comment by amanshah28** [comment]
Me too

**Comment by offline-first** [comment]
PR #19

**Comment by hadukin** [comment]
@offline-first thanks for the help.

fixed version (1.6.1) available at pub.dev

**Comment by Tristannos** [comment]
Still having the problem!!
but if i change:  
    SchedulerBinding.instance.addPostFrameCallback(postFrameCallback);
to this:
    SchedulerBinding.instance?.addPostFrameCallback(postFrameCallback);

it works.

**Comment by offline-first** [comment]
@Tristannos  update to latest flutter version ;)
